#!/bin/bash

tmpfile=$(mktemp /tmp/pipsta.XXXXXXXXX)
echo "a file: $tmpfile"

printf '%s\0SET dither%s\15' > $tmpfile
printf '%s\0SET rotate%s\15' >> $tmpfile
printf '%s\0.SCR%s\15' >> $tmpfile
cat $1 >> $tmpfile

cat $tmpfile | netcat -c minnie 65432

rm $tmpfile
